modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/KubeJS-Immersive-Engineering/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_immersive_engineering"
version = "${version}"
displayName = "KubeJS Immersive Engineering"
authors = "LatvianModder"
description = '''
KubeJS integration for Immersive Engineering.
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_immersive_engineering]]
modId = "kubejs"
mandatory = true
versionRange = "[1902.6.0-build.140,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_immersive_engineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.19.2-9.2.0-162,)"
ordering = "AFTER"
side = "BOTH"