modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/KubeJS-Immersive-Engineering/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_immersive_engineering"
version = "${version}"
displayName = "KubeJS Immersive Engineering"
authors = "LatvianModder"
description = '''
KubeJS Thermal Expansion integration
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_immersive_engineering]]
modId = "kubejs"
mandatory = true
versionRange = "[1801.4.2-,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_immersive_engineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"