modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/KubeJS-Immersive-Engineering/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_immersive_engineering"
version = "${version}"
displayName = "KubeJS Immersive Engineering"
authors = "LatvianModder"
description = '''
KubeJS integration for Immersive Engineering.
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_immersive_engineering]]
modId = "kubejs"
mandatory = true
versionRange = "[1802.5.1-build.331,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_immersive_engineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"